### PR TITLE
Added skip editing option

### LINKED ISSUE #323: [Feat] - Add Skip Editing option to CropImageContractOptions
I've been using the original library and recently discovered this one. Since I required a feature in the original library I've added it to my project and modified the source code.

This is the feature I had added to the original library. I had an option to skip editing the image entirely because I don't require users to edit the images everywhere in my app. I basically want to skip the editing step. So if I pass an option like `setSkipEditing(true)` the CropImageActivity should directly return the entire image (after any processing) without any user interaction.

I'll try and submit a PR

### PR DESCRIPTION
**Pull request by Devenom1**
closes #323 

# Added an option to skip editing the selected image entirely when not required[New Feature]
## Description:
The user can now set an option to skip editing (cropping, flipping or rotating) the image entirely when not required. This can be useful when some places in your app don't require the image to be edited but you still want to use this library because of it's great functionality of picking and choosing images. This will help reduce user interactions in such cases

### CODE REVIEW

**Review by Canato — CHANGES_REQUESTED** [review]
Thanks for the PR =D

Discussion on the linked issue

Don't forget the changelog update

**Comment by Canato** [comment]
_branch need to be rebased for latest main_

**Comment by Devenom1** [comment]
> _branch need to be rebased for latest main_

All Done @Canato 👍🏻

**Review by Canato — APPROVED** [review]
🚀

**Pull request merged**
