### PR TITLE
Reproduce Bug #203

### PR DESCRIPTION
**Pull request by James471**
Reproducing the bug in #203 

## Bug
Doesn't set the right initial crop window rectangle

### Reproduce
Check #203 

### How the bug was solved:
Unsolved

### CODE REVIEW

**Comment by Canato** [comment]
looking it

**Comment by Canato** [comment]
@James471 I did some tests, and look like you are trying to crop a `Rect` that is bigger than the image/window. The library try to fix this to keep it inside the screen, but the result is not what you setup.

Making the Rect smaller worked for me. without any other change, let me know what you think

Screenshot 2021-09-06 at 19 09 15

**Comment by James471** [comment]
> 
> 
> @James471 I did some tests, and look like you are trying to crop a `Rect` that is bigger than the image/window. The library try to fix this to keep it inside the screen, but the result is not what you setup.
> 
> Making the Rect smaller worked for me. without any other change, let me know what you think
> 
> Screenshot 2021-09-06 at 19 09 15


Screenshot 2021-09-15 232835
Here, the cropping rectangle is `Rect(1239, 544, 2386, 1036)` while the image rectangle is `Rect(0, 0, 4624, 3468)`. I think the cropping rectangle lies well within the image. Does `setInitialRectangle()` set the rectangle relative to the parent window and not the original image?

**Comment by Canato** [comment]
Nw @James471 we all should focus on real life over our screens a little more XD

> Does setInitialRectangle() set the rectangle relative to the parent window

Exactly, what can be miss leading. Would be great to improve this if you feel like @@

**Comment by James471** [comment]
Rightly said.
Thanks a lot for your time. I will close the PR now.

**Pull request closed without merging**
