### PR TITLE
Add option to disable translation of the crop window

### LINKED ISSUE #78: [Feat] - Ability to disable dragging of crop window from the center (i.e. disable translation - to use the mathematical meaning of "translate")
**Is your feature request related to a problem? Please describe.**
This is a specific use-case that I have. It's particularly convenient when used in conjunction with #76.

**Describe the solution you'd like**
The ability to disable (in XML, activity builder or via methods on the CropImageView) the ability to translate the crop window.

**Describe alternatives you've considered**
None.

**Additional context**
As with my other issue, see the PlayScore 2 app for iOS. I wonder if you can guess what app I'm working on? :)

### PR DESCRIPTION
**Pull request by chriscoomber**
close #78 

# Template 1 [New Feature]
## Description:
Added new option to disable translating of the crop window by dragging the center.

Most of the changes here were boilerplate changes. I used the `multiTouch` option as a template to make sure I added the option to all the places it was required, such as XML, CropImageView and ActivityBuilder. I also added the toggle to the sample app.

The functional change is that, when this toggle is disabled, dragging from the center of the crop window does nothing.

## Check list for the Code Reviewer:
* [ ] CHANGELOG
* [ ] README
* [ ] Wiki
* [ ] Version Number

### CODE REVIEW

**Comment by chriscoomber** [comment]
This conflicts very minorly with #76, so I suggest we merge than one first and then I'll fix up the conflicts.

**Comment by chriscoomber** [comment]
Meta point: I realize that these features might not be popular - they're just something I need that I might as well share. I definitely want to use this library rather than rolling my own as it is high quality. This is the last feature that I need to add. Feel free to push back against this if you don't think this feature should be added - it's no problem for me to fork the repo.

**Comment by Canato** [comment]
@chriscoomber 
> Meta point: I realize that these features might not be popular - they're just something I need that I might as well share. I definitely want to use this library rather than rolling my own as it is high quality. This is the last feature that I need to add. Feel free to push back against this if you don't think this feature should be added - it's no problem for me to fork the repo.

I believe it is not a problem, since it can be useful for more people. 

We just need to be sure that the default value keeps the expected behaviour.

Because of the possible misinterpretation of `ImageTranslation` how about we name the method `lockCenter` or `disableCropCenterMove`?

**Comment by chriscoomber** [comment]
> Because of the possible misinterpretation of ImageTranslation how about we name the method lockCenter or disableCropCenterMove?

I've renamed it `centerMoveEnabled`, and the XML attribute is `cropCenterMoveEnabled`.

**Review by Canato — COMMENTED** [review]
Looking good! 

Let me know, when is over.

Please don't forget to add `setCenterMoveEnabled()` into `Sample/CameraFragment` on the methods `startCameraWithoutUri` and `startCameraWithUri`

**Comment by chriscoomber** [comment]
@Canato OK I think this is done. I can't see anything else that needs changing.

**Review by Canato — APPROVED** [review]
Great work!

**Pull request merged**
